[package]
name = "telegram_tagger"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
log = "0.4"
pretty_env_logger = "0.5"
rusqlite = "0.38.0"
teloxide = { version = "0.17.0", features = ["macros"] }
tokio = { version = "1.49.0", features = ["full"]}
